version: "3.1"

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3366:3306
    volumes:
      - ./volume:/bitnami/mariadb/data
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: root
