export enum Roles {
  ADMIN = 'ADMIN',
  USER = 'USER',
}

export enum Errors {
  ERROR_INVALID_SING_IN = 'ERROR_INVALID_SING_IN',
  ERROR_MISSING_USERNAME = 'ERROR_MISSING_USERNAME',
  ERROR_MISSING_PASSWORD = 'ERROR_MISSING_PASSWORD',
  ERROR_NICKNAME_IN_USE = 'ERROR_NICKNAME_IN_USE',
}

export enum RealmSchemas {
  USER = 'User',
  ROOM = 'Room',
}
