export enum Roles {
  ADMIN = 'ADMIN',
  USER = 'USER',
}

export enum Errors {
  ERROR_INVALID_SING_IN = 'ERROR_INVALID_SING_IN',
  ERROR_MISSING_USERNAME = 'ERROR_MISSING_USERNAME',
  ERROR_MISSING_PASSWORD = 'ERROR_MISSING_PASSWORD',
  ERROR_USERNAME_IN_USE = 'ERROR_USERNAME_IN_USE',
  ERROR_NEW_USER_NOT_CREATED = 'ERROR_NEW_USER_NOT_CREATED',
}

export enum RealmSchemas {
  USER = 'User',
  USER_META = 'UserMeta',
  ROOMS = 'Rooms',
}
